apiVersion: wordpress.codingbee.net/v1
kind: Mysql
metadata:
  name: mysql-sample
spec:
  environment:
    mysql_root_password: rootpasswod
    mysql_database: mywpdb
    mysql_user: adminuser
    mysql_password: dbpassword